### PR TITLE
Update scores It's AI

### PR DESCRIPTION
**Pull request by sergak0**

### CODE REVIEW

**Comment by sergak0** [comment]
Thanks for merging. How much time does it take to update info on the leaderboard?

**Comment by liamdugan** [comment]
Normally it should be instant, but I accidentally merged your pull request before approving the evaluation run so it's not updating your scores (thus the evaluation error). I'll fix this tomorrow.

**Comment by sergak0** [comment]
Should I resubmit the PR or no need?

**Comment by liamdugan** [comment]
Yes can you resubmit the PR? @sergak0  That would be helpful

**Comment by sergak0** [comment]
done

**Pull request merged**
