### PR TITLE
你的提交信息

### PR DESCRIPTION
**Pull request by Shixuan-Ma**

### CODE REVIEW

**Comment by liamdugan** [comment]
Hey @Shixuan-Ma just wanted to confirm that you are not planning on submitting to the Shared Task at COLING. If you want to be on the main leaderboard you will be disqualified from the shared task. 

If that's okay then I'll approve your PR and add your model.

**Comment by Shixuan-Ma** [comment]
Thank you for your reply. In fact, this is a test submission, and I do not intend to submit the results of this method to COLING 2025. You can submit it to the leaderboard. An additional question: if I want to submit to COLING 2025, when should I start submitting?

**Comment by Shixuan-Ma** [comment]
Thank you for your reply. In fact, this was a test submission. I do indeed want to participate in COLING 2025. You don't need to approve this pull request. By the way, if I want to submit to COLING 2025, when should I start the submission process?

**Comment by liamdugan** [comment]
@Shixuan-Ma You can start the submission process now. We just released an update to the shared task repository with more detailed submission instructions [here](https://github.com/liamdugan/COLING-2025-Workshop-on-MGT-Detection-Task-3?tab=readme-ov-file#competition). It should be as simple as opening the same pull request but on the other repository with your current predictions.json and metadata.json.

**Comment by Shixuan-Ma** [comment]
Thanks!

**Pull request closed without merging**
