### PR TITLE
It's AI detector leaderboard submission

### PR DESCRIPTION
**Pull request by sergak0**

### CODE REVIEW

**Comment by liamdugan** [comment]
Congrats on the new SOTA! Merged.

**Comment by sergak0** [comment]
Thanks! By the way, I've seen that in the paper you've also scored commercial ai-detectors, but I haven't found them in the leaderboard - is there a way to compare our solution with theirs?

**Comment by liamdugan** [comment]
Yes. The reason why they aren't included on the leaderboard is because we were only able to test a small portion of our test set on the commercial detectors due to budget constraints. We're currently working with these companies to get more credits so that we can add them to the leaderboard as well. We hope to add them soon.

**Comment by sergak0** [comment]
Glad to hear that you are going to add them too. Anyway great work with RAID dataset - really impressed with the amount and diversity of data that you've collected and first ai-detection leaderboard that you've made.

**Comment by liamdugan** [comment]
Thank you! And thanks for submitting :)

**Comment by AIApprentice101** [comment]
Thank you @liamdugan for the prompt update of the leaderboard. It is great to have a new SOTA method. Congrats @sergak0 

I notice on your github page (https://github.com/It-s-AI/llm-detection) that there're two baseline models, the perplexity-logistic regression model, and the finetuned Deberta model. Is the Deberta model the SOTA submission here? 

Btw, I love your idea of using Bittensor subset for the AI detection task.

**Comment by sergak0** [comment]
@AIApprentice101 yeah, it's the result from subnet 32, so I don't know what's under the hood.

> Btw, I love your idea of using Bittensor subnet for the AI detection task.

Thanks, hope to make our detector even better in future.

**Pull request merged**
