### PR TITLE
SuperAnnotate AI Detector Submission

### PR DESCRIPTION
**Pull request by SA-Yur-or**

### CODE REVIEW

**Comment by liamdugan** [comment]
Thanks for submitting to RAID @SA-Yur-or ! Just wanted to confirm that you are not planning on submitting to the [Shared Task at COLING](https://github.com/liamdugan/COLING-2025-Workshop-on-MGT-Detection-Task-3). If you want to be on the main RAID leaderboard you will be disqualified from the shared task.

If that's okay then I'll approve your PR and add your model.

**Comment by SA-Yur-or** [comment]
Thank you for the clarification!
I confirm that we're not planning to submit to the Shared Task at COLING.
However, I wanted to ask if it would be possible to see the validation results before my submission is merged.
Thank you again for your support!

**Comment by liamdugan** [comment]
Sure thing, I'll approve the validation run and then let me know if you want to merge.

**Comment by SA-Yur-or** [comment]
Looks good—this is roughly what we expected. You can go ahead and merge it.

Quick question out of context: is the distribution of models, attacks, and domains consistent between the train and test datasets in RAID?

**Comment by liamdugan** [comment]
Thanks @SA-Yur-or ! We'll merge you in.

Also yes, the distribution of our test data is identical to train. We sampled examples from each domain and model and made sure that the ratio of each is exactly the same as in the training data.

**Pull request merged**
